version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/packages/*"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Monday
    target-branch: "main"